#!/usr/bin/env bash

if [ -z $1 ]; then
  echo "Please provide path to module which you would like to certify. The path must be relative to eshop's module path (e.g. mycompanyvendor/mymodulename)."
  exit 1
fi

SHOP_PATH="{{ eshop_path.source }}/"
MODULE_PATH="{{ eshop_path.modules }}/$1"

ADDITIONAL_TEST_PATHS="" RUN_TESTS_FOR_SHOP=0 PARTIAL_MODULE_PATHS="$1" ${SHOP_PATH}vendor/bin/runtests-coverage

cd {{ eshop.sdk.path }}/module_certification_tools/
MODULEPATH=${MODULE_PATH} CFG_CLOVER_LOCATION=${MODULE_PATH}/tests/reports/clover.xml ./run.sh
